
services:
  app:
    container_name: nestJs-shop
    # Build the app service using the Dockerfile in the current directory
    build:
      context: .
      dockerfile: Dockerfile
    # Expose and map port 3000 of the container to port 3000 on the host
    ports:
      - "3000:3000"
    # Mount the current directory to /usr/src/app in the container for live code updates
    # Also mount node_modules to prevent overwriting it with the local directory's content
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    
    environment:
      - NODE_ENV=development
    command: npm run start:dev
    # Ensure the app service starts only after the db_posgres service is ready
    depends_on:
      - db_posgres
    # Load environment variables from the .env file
    env_file:
      - .env
    # Use the custom 'app-network' network for internal communication
    networks:
      - app-network

  db_posgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: shop_user
      POSTGRES_PASSWORD: shop_password
      POSTGRES_DB: shop_database
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:


 


networks:
  app-network:
    driver: bridge
